#!/bin/bash

set -e

script='/etc/NetworkManager/dispatcher.d/99proxydriver.sh'
conf_dir='/etc/proxydriver.d'
bashrc='/etc/bash.bashrc'
proxy_env='/etc/environment'

rm "$script"

if [ "$1" = "purge" ]
then
	rm -r "$conf_dir"
fi

sed -i '### proxydriver add' "$bashrc"

