#!/bin/bash

set -e

src='/usr/share/doc/proxydriver/proxydriver.sh'
dst='/etc/NetworkManager/dispatcher.d/99proxydriver.sh'
bashrc='/etc/bash.bashrc'
proxy_env='/etc/environment'

install -m 755 -o 0 -g 0 "$src" "$dst"

new_bash=mktemp

grep -v '### proxydriver add' "$bashrc" > "$new_bash"
echo "[ -f \"$proxy_env\" ] && while read l; do export \$l; done < \"$proxy_env\" ### proxydriver add" >> "$new_bash"
install -m 644 -o 0 -g 0 "$new_bash" "$bashrc"
rm "$new_bash"
