#!/bin/bash
set -e

conf_dir='/etc/proxydriver.d'
bashrc='/etc/bash.bashrc'
proxy_env='/etc/environment'

rm -rf '/etc/NetworkManager/dispatcher.d/99proxydriver.sh'

if [ "$1" = "purge" ]
then
  rm -rf "$conf_dir"
fi

sed -i '### proxydriver add' "$bashrc"

